# Generated by Django 2.2.1 on 2019-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialescolar',
            name='valor',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
