# Generated by Django 2.2.1 on 2019-05-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_auto_20190526_0451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialEscolar',
        ),
    ]
